version: "3.8"

services:
  mysql:
    image: mysql:8.0.21
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: mysql-user
      MYSQL_PASSWORD: mysql-password
      MYSQL_ROOT_PASSWORD: mysql-root-password
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - mysql-network

networks:
  mysql-network: {}

volumes:
  mysql-volume: {}
