version: "3.8"

services:
  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postgres-network

networks:
  postgres-network: {}

volumes:
  postgres-volume: {}
