version: "3.8"

services:
  mongo:
    image: mongo:4.4.0-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-root
      MONGO_INITDB_ROOT_PASSWORD: mongo-root-pw
    networks:
      - mongo-network
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo-root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo-root-pw
    depends_on:
      - mongo
    networks:
      - mongo-network
    ports:
      - 8081:8081

networks:
  mongo-network: {}

volumes:
  mongo-volume: {}
