version: "3.8"

services:
  redis:
    image: redis:6.0.6-alpine
    networks:
      - redis-network
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/data

networks:
  redis-network: {}

volumes:
  redis-volume: {}
